"""empty message

Revision ID: e8794dc419d1
Revises: 25131e437286
Create Date: 2024-06-18 12:01:20.267172

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e8794dc419d1'
down_revision = '25131e437286'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('contract_elements', schema=None) as batch_op:
        batch_op.create_unique_constraint('_contract_element_name_uc', ['name'])

    with op.batch_alter_table('contract_templates', schema=None) as batch_op:
        batch_op.create_unique_constraint('_contract_template_name_uc', ['name'])

    with op.batch_alter_table('employees', schema=None) as batch_op:
        batch_op.create_unique_constraint('_employee_email_uc', ['email'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('employees', schema=None) as batch_op:
        batch_op.drop_constraint('_employee_email_uc', type_='unique')

    with op.batch_alter_table('contract_templates', schema=None) as batch_op:
        batch_op.drop_constraint('_contract_template_name_uc', type_='unique')

    with op.batch_alter_table('contract_elements', schema=None) as batch_op:
        batch_op.drop_constraint('_contract_element_name_uc', type_='unique')

    # ### end Alembic commands ###
